id: deeplabv3_resnet101
pretrained:
seed: 42

model:
    name: DeeplabV3
    args:
      numclasses: 91
      
optimizer:
    name: Adam
    args:
        lr: 0.00001
        # momentum: 0.9
        # nesterov: True 
        # <argument keyword>: <argument value>
        # ... more args
loss:
    name: CrossEntropyLoss
    args:
        #nclasses: 40
        # ... more args
metric:
    - name: PixelAccuracy
      args:
         # nclasses: 11
         nclasses: 91

scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 100
        verbose: True

dataset:
    train:
        
        name: COCODataset
        args:
            img_folder: CocoDataset/val2017
            annot_file: CocoDataset/annotations/val_split_train_instances.json
            # img_folder: /home/nero/YoutubeVIS21/train/JPEGImages
            # annot_file: /home/nero/YoutubeVIS21/train/train_instances_frames.json
            max_annot: 1000
          
        loader:
            name: DataLoader
            args:
                batch_size: 10
                num_workers: 4
                shuffle: True
    val:
        name: COCODataset
        args:
            img_folder: CocoDataset/val2017
            annot_file: CocoDataset/annotations/val_split_val_instances.json
            max_annot: 1000
        loader:
            name: DataLoader
            args:
                batch_size: 10
                num_workers: 4
                shuffle: False 

trainer:
    nepochs: 100
    val_step: 1
    backward_step: 4
    save_dir: runs